### ISSUE TITLE
Bugfix - do not exit with error when config is empty

### ISSUE THREAD

**Issue by jaroslav-kubicek** [falsecz/cson-config#4]
When I load config file that is empty, incomprehensible error is thrown and program exits with error:

```
TypeError: Cannot read property 'stack' of undefined
  at Object.exports.load (/Users/kubajz/projects/cheddar/node_modules/cson-config/index.coffee:51:5)
```

The problem lies in this condition: `if c.stack?`, because variable c is undefined in case of empty file.

**Comment by falsecz** [comment]
Landed in 0.1.13
